Work here
djordje997/Pascal-Triangle pull request #1
Opened 2022-02-08 18:42 UTC by djordje997

Created fist version of project

2022-02-09 12:41 UTC, basti requested changes
@djordje997 ok, this is a very good first draft. 👏 

I have an additional request... Often objects have different methods named `to_*` that will convert the object to something else. `to_s` will typically generate a string representation of an object. `to_a` might be used to generate an array representation of an object. Can you please add those two methods to PascalTriangle class? `to_s` should return a formated string as described in the assignment. `to_a` should return an array of arrays representing the triangle rows (i.e. `[[1], [1, 1], [1,2,1], ...]`).

2022-02-09 12:41 UTC, basti commented on lib/triangle.rb
> +  def create_triangle()
@djordje997 you don't need `()`. See: https://rubystyle.guide/#method-parens

2022-02-09 12:41 UTC, basti commented on bin/pascal_main.rb
> +number_of_rows = user_input()
@djordje997 can you please also add ability, similar like you did in Rot assignment, to pass the argument directly from command line?

2022-02-09 12:41 UTC, basti commented on bin/pascal_main.rb
> +def print_triangle(triangle)
@djordje997 it's a good idea to create a helper method to format the triangle. 👍 I would just change for it to receive the object itself and get what it needs from it.

2022-02-09 12:41 UTC, basti commented on lib/triangle.rb
> +    triangle = []
@djordje997 can you cache the triangle value? Once the triangle is calculated it should store it and be able to return it without recalculating it again.

2022-02-09 12:41 UTC, basti commented on lib/triangle.rb
> +    ([0] + row).zip(row + [0]).collect { |a, b| a + b }
@djordje997 how did you come up with this formula? What does it do?

2022-02-09 16:20 UTC, djordje997 commented on lib/triangle.rb
> +    ([0] + row).zip(row + [0]).collect { |a, b| a + b }
I fount this one online the point behind this line is that it takes row lets say row is [1, 2, 1] the method than we will create collection of [0, 1, 2, 1] and [1, 2, 1, 0] and with method zip it will create nested array from elements  of 2 collections. It will take first element from first collection and first element from second colection and it will create pair of those two elements and so on.., Result would be something like [[0, 1,],[1, 2], [2, 1], [1, 0]]. After that collect method will put these pairs together a=0 b =1 a+b and so on for each pair and final result would be array of [1, 3, 3, 1] it represents next row

2022-02-09 16:31 UTC, djordje997 commented
> @djordje997 ok, this is a very good first draft. 👏
> 
> I have an additional request... Often objects have different methods named `to_*` that will convert the object to something else. `to_s` will typically generate a string representation of an object. `to_a` might be used to generate an array representation of an object. Can you please add those two methods to PascalTriangle class? `to_s` should return a formated string as described in the assignment. `to_a` should return an array of arrays representing the triangle rows (i.e. `[[1], [1, 1], [1,2,1], ...]`).



> @djordje997 ok, this is a very good first draft. 👏
> 
> I have an additional request... Often objects have different methods named `to_*` that will convert the object to something else. `to_s` will typically generate a string representation of an object. `to_a` might be used to generate an array representation of an object. Can you please add those two methods to PascalTriangle class? `to_s` should return a formated string as described in the assignment. `to_a` should return an array of arrays representing the triangle rows (i.e. `[[1], [1, 1], [1,2,1], ...]`).

Sorry i think i didn't understand this one whould you like me to create additional method "to_s" and to move content of "print_triangle" method to the "to_s" method? and for to_a i think i don't understant at all

2022-02-10 09:39 UTC, basti requested changes

2022-02-10 09:39 UTC, basti commented on bin/pascal_main.rb
> +def user_input ()
@djordje997 https://rubystyle.guide/#method-parens - again.

2022-02-10 09:39 UTC, basti commented on bin/pascal_main.rb
> +  number_of_rows = user_input()
@djordje997 https://rubystyle.guide/#method-parens - again.

2022-02-10 09:39 UTC, basti commented on bin/pascal_main.rb
> +triangle_generator.create_triangle()
@djordje997 https://rubystyle.guide/#method-parens - again.

2022-02-10 09:39 UTC, basti commented on lib/triangle.rb
> +    ([0] + row).zip(row + [0]).collect { |a, b| a + b }
👍

2022-02-10 09:39 UTC, basti commented on lib/triangle.rb
> +  attr_accessor :triangle
@djordje997 this will cause problems. Triangle will be empty if the outside caller doesn't remember to call `create_triangle` before trying to get `triangle`. You always want to hide as much of the inner workings of a class as possible. Other objects don't need to know what the class must do before returning a triangle.

In this case, that would mean you need to create a custom getter method (i.e. `def triangle`) that would calculate the triangle (if needed) and return it.

2022-02-10 21:11 UTC, basti requested changes
@djordje997 to_a and to_s are what I expected/asked for. However, you ignored one important part regarding caching calculated values. See my comment in the code.

2022-02-10 21:11 UTC, basti commented on lib/triangle.rb
> +    triangle = create_triangle
@djordje997 this will always recalculate the whole triangle. There's no caching here. Please read carefully what I wrote here: https://github.com/djordje997/Pascal-Triangle/pull/1#discussion_r803477285 - I wrote exactly what method you need to implement.

2022-02-10 21:11 UTC, basti commented on spec/pascal_triangle_spec.rb
> +  end
@djordje997 usually you wouldn't have tests like these. They give an output like this:

```
PascalTriangle create triangle of 5 rows
  first row is [1]
  second row is [1, 1]
  third row is [1, 2, 1]
  fourth row is [1, 3, 3, 1]
  fifth row is [1, 4, 6, 4, 1]
```

Not very readable/usable. It doesn't say what method you are testing. 

For this particular case I would have something like:

```
describe "#to_a" do
  it "returns an array" do
    # ...spec goes here...
  end

  context "Generates different length triangles" do
    it "returns a single row triangle"

    it "returns a three-row triangle"

    it "returns a five-row triangle"
  end
end

describe "#to_s" do
  # specs go here
end
```

Something along those lines. Generally, you would want to cover the borderline cases and at least one in the "middle". I picked 1, 3, and 5 rows triangles in my example.

In this particular case, there are no real borderline cases, except for the 1-row triangle. I picked 1, 3, and 5-row cases as a representative. It could have been easily 1, 5, 15. In this case, as I said, there are no real borderline cases, just cases that represent requirements.

Can you please refactor specs to be more meaningful?

2022-02-19 21:31 UTC, basti commented
@djordje997 any update on this? Do you know what to do?

2022-02-21 18:05 UTC, djordje997 commented
> @djordje997 any update on this? Do you know what to do?

i thought when object is created it will have @triangle witch will be empty array and than in method to_a i just need to check if @trianglee contains elements of array for purpose of cheking if object is already created and then return it, i don't like this code i wanted to find method to check that maybe defined? method... As for tests i will update tomorrow and sorry for delay

2022-02-25 11:07 UTC, basti requested changes

2022-03-01 15:10 UTC, basti requested changes
@djordje997 ok, I think this is the last set of changes. 👍

2022-03-01 15:10 UTC, basti commented on lib/triangle.rb
> +  end
@djordje997 most of the time when performing memoization you will do it through a custom getter method that has the same name as the instance variable. In this case, it means you need a method `triangle` (can be private).

A nice side effect is that in other methods (e.g. here: https://github.com/djordje997/Pascal-Triangle/pull/1/files#diff-562891baeee40b072c3250d7631cfba88ec6ce2ffe305751c590375e50b306c0R13) you don't need a separate local variable just to iterate over.

2022-03-01 15:10 UTC, basti commented on lib/triangle.rb
> +      string_triangle << " " * spacing
@djordje997 try avoiding using variable data type (i.e. string) in the name of a variable. A better name here would be `formatted_triangle`.

2022-03-01 15:10 UTC, basti commented on lib/triangle.rb
> +      spacing = (longest_row_length - current_length) / 2
@djordje997 `current_length` variable is used only once. I don't think it adds to the code readability or brewity to have a separate local variable. Consider these two lines:

```
spacing = (longest_row_length - current_length) / 2

spacing = (longest_row_length - current_row_formated.length) / 2
```

2022-03-01 15:10 UTC, basti commented on lib/triangle.rb
> +      string_triangle += "\n"
@djordje997 might make sense to move most of this code into a separate method, say: `format_triangle_row`.

2022-03-02 09:55 UTC, basti requested changes

2022-03-02 09:55 UTC, basti commented on lib/triangle.rb
> +    def to_a
@djordje997 I am not sure if you just didn't understand what I was saying in https://github.com/djordje997/Pascal-Triangle/pull/1#discussion_r816852021 or if you forgot to do it. I didn't ask for `to_a` to be private. I asked for you to implement a new method, more specifically a getter method that has memoization to speeds things up (if you are not sure what a getter method is let me know; in general, whenever I reference something that you don't know what it is let me know).

Basically, what I am after is described in the `Super basic memoization` section of this blog post: https://www.justinweiss.com/articles/4-simple-memoization-patterns-in-ruby-and-one-gem/

You need to have a public `to_a` method that returns an array representation of the object. You need to have `triangle` method which sets and returns `@triangle` instance variable with memoization. The most basic implementation would be:

```
def triangle
  @triangle ||= create_triangle
end
```

Also in `create_triangle` you should not be setting `@triangle` variable, that's usually done in the method that performs memoization (we can get into the details why in person).

2022-03-07 15:07 UTC, basti requested changes
@djordje997 can you please fix these two indentations "issues"?

2022-03-08 11:31 UTC, merged